root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # The compiled binary will be placed inside the 'tmp' directory
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/main"  # Updated to point to the main package
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []  # You can add directories to include if needed
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[watch]
  # Watch the 'cmd' directory for changes to Go files
  dirs = ["cmd", "doctors", "internal", "pkg"]
  # Include all .go files in the project to trigger rebuild on changes
  extensions = ["go"]
